# Introducción a Pandas

En este notebook aprenderemos cómo leer datos en un `DataFrame` y algunas herramientas básicas de Pandas.

## Instalación y Importación de Pandas
Para usar Pandas, primero debemos instalarlo (si no lo tenemos) y luego importarlo en nuestro código.

In [ ]:
# Instalar pandas (si no está instalado)
!pip install pandas

In [2]:
# Importar pandas
import pandas as pd

## Lectura de Datos con Pandas
Podemos leer diferentes tipos de archivos como CSV, Excel o JSON usando Pandas.

In [4]:
df = pd.read_excel('CIE10.xlsx')  
df

,COD_3,DESRIPCION CATEGORIAS DE TRES CARACTERES,COD_4,DESCRIPCION CODIGOS DE CUATRO CARACTERES
0,A00,COLERA,A000,"COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO CH..."
1,NaN,NaN,A001,"COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO EL..."
2,NaN,NaN,A009,COLERA NO ESPECIFICADO
3,A01,FIEBRES TIFOIDEA Y PARATIFOIDEA,A010,FIEBRE TIFOIDEA
4,NaN,NaN,A011,FIEBRE PARATIFOIDEA A
...,...,...,...,...
12418,NaN,NaN,Z991,DEPENDENCIA DE RESPIRADOR
12419,NaN,NaN,Z992,DEPENDENCIA DE DIALISIS RENAL
12420,NaN,NaN,Z993,DEPENDENCIA DE SILLA DE RUEDAS
12421,NaN,NaN,Z998,DEPENDENCIA DE OTRAS MAQUINAS Y DISPOSITIVOS C...
12422,NaN,NaN,Z999,DEPENDENCIA DE MAQUINA Y DISPOSITIVO CAPACITAN...

## EDA Básico del DataFrame

In [9]:
df.head()

,COD_3,DESRIPCION CATEGORIAS DE TRES CARACTERES,COD_4,DESCRIPCION CODIGOS DE CUATRO CARACTERES
0,A00,COLERA,A000,"COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO CH..."
1,NaN,NaN,A001,"COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO EL..."
2,NaN,NaN,A009,COLERA NO ESPECIFICADO
3,A01,FIEBRES TIFOIDEA Y PARATIFOIDEA,A010,FIEBRE TIFOIDEA
4,NaN,NaN,A011,FIEBRE PARATIFOIDEA A

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12423 entries, 0 to 12422
Data columns (total 4 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   COD_3                                     2037 non-null   object
 1   DESRIPCION CATEGORIAS DE TRES CARACTERES  2036 non-null   object
 2   COD_4                                     12423 non-null  object
 3   DESCRIPCION CODIGOS DE CUATRO CARACTERES  12423 non-null  object
dtypes: object(4)
memory usage: 388.3+ KB

In [11]:
df.describe()

,COD_3,DESRIPCION CATEGORIAS DE TRES CARACTERES,COD_4,DESCRIPCION CODIGOS DE CUATRO CARACTERES
count,2037,2036,12423,12423
unique,2037,2036,12423,12420
top,A00,COLERA,A000,OTRAS MALFORMACIONES CONGENITAS DE LA LARINGE
freq,1,1,1,2

## Selección y Filtrado de Datos

In [ ]:
nombre_columna = 'COD_3'
print(df[nombre_columna])

In [14]:
(df[['COD_3', 'COD_4']])

      COD_3 COD_4
0       A00  A000
1       NaN  A001
2       NaN  A009
3       A01  A010
4       NaN  A011
...     ...   ...
12418   NaN  Z991
12419   NaN  Z992
12420   NaN  Z993
12421   NaN  Z998
12422   NaN  Z999

[12423 rows x 2 columns]

In [17]:
df[df['COD_3']=='A01']

,COD_3,DESRIPCION CATEGORIAS DE TRES CARACTERES,COD_4,DESCRIPCION CODIGOS DE CUATRO CARACTERES
3,A01,FIEBRES TIFOIDEA Y PARATIFOIDEA,A010,FIEBRE TIFOIDEA

## Operaciones Básicas con Columnas

In [18]:
df['nueva_columna'] = df['columna1'] * 2

KeyError: 'columna1'

In [ ]:
# Eliminar una columna
df = df.drop(columns=['columna_a_eliminar'])
print(df.head())

## Conclusión
Hemos aprendido cómo leer datos en un `DataFrame` y aplicar herramientas básicas en Pandas. Esto es fundamental para el análisis y manipulación de datos en Python.